name: "DNS-O-Matic"
description: "Iñaki's DNS-O-Matic Addon"
version: "1.0.0"
url: "https://github.com/iAbadia/ha-addons"
slug: "dnsomatic"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
schema:
  hostname: str
  domain: str
  email: str
  api_token: str
  update_interval: int
