name: "DNS-O-Matic"
description: "Iñaki's DNS-O-Matic Addon"
version: "1.0.0"
url: "https://github.com/iAbadia/ha-addons/tree/main/dnsomatic"
slug: "dnsomatic"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
schema:
  hostname: list(dynamic)
  domain: str
  email: match(^[\w-\.]+@([\w-]+\.)+[\w-]{2,4}$)
  api_token: str
  update_interval: int
